<html>
<head>
  <title>Panta Rhei - Administration</title>
  	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<script src="<?=$this->url('home')?>vendor/js/bootstrap-3.3.7.min.js"></script>
    <!--<script src="<?//=$this->url('home')?>js/menu.js"></script>-->
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="<?=$this->url('home')?>vendor/css/bootstrap-3.3.7.min.css" >
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main.css" media="screen" />
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main_admin.css" media="screen" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
<body>
<div class="banner">
  <h1>Administration</h1><br />

  <?php
	// Set up breadcrumbs:
    if (isset($this->layout()->breadcrumbs)) {
		$this->layout()->breadcrumbs = '<a href="' .  $this->url('home') . '" style="float:left;color:white;">Home > </a>'   
		                              . $this->layout()->breadcrumbs;
		echo $this->layout()->breadcrumbs;
	}
	else
	{
		$this->layout()->breadcrumbs = '<a href="' .  $this->url('home') . '" style="float:left;color:white;">Home > </a>';
		echo $this->layout()->breadcrumbs;
	}
  ?>
</div>

<!-- Fixed navbar -->
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right pull-left">
            <li class="dropdown">
				<a href="#" class="dropdown-toggle " data-toggle="dropdown">Work<b class="caret"></b></a>			  
				<ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_work') ?>">New</a></li>
                <li><a href="<?php echo $this->url('search_work') ?>">Search</a></li>
				<li><a href="<?php echo $this->url('manage_work') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('manage_work') ?><?= '?action=review' ?>">Review</a></li>
				<li><a href="<?php echo $this->url('manage_work') ?><?= '?action=classify' ?>">Classify</a></li>
				</ul>
			</li>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Work Type<b class="caret"></b></a>
				<ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_worktype') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('manage_worktype') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('attributes_worktype') ?>">Attributes</a></li>
				</ul>
            </li>       
            <li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Classification<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_classification') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('manage_classification') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_classification') ?><?= '?action=merge_classification' ?>">Merge</a></li>				
				<li><a href="<?php echo $this->url('exportlist_classification') ?><?='?action=export_classification'?>">Export List</a></li>
              </ul>
            </li>  			
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Agent<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_agent') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('find_agent') ?>">Find</a></li>
				<li><a href="<?php echo $this->url('manage_agent') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_agent') ?><?='?action=merge'?>">Merge</a></li>
              </ul>
            </li>  
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Agent Type<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_agenttype') ?><?='?action=new'?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_agenttype') ?>">Manage</a></li>
              </ul>
            </li> 
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Publisher<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_publisher') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('find_publisher') ?>">Find</a></li>
				<li><a href="<?php echo $this->url('manage_publisher') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_publisher') ?>">Merge</a></li>
              </ul>
            </li> 
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Language<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_language') ?><?='?action=new'?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_language') ?>">Manage</a></li>
              </ul>
            </li> 
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_user') ?><?='?action=new'?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_users') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('access_users') ?>">Access</a></li>
              </ul>
            </li> 
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Preferences<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('changepassword_preferences') ?><?='?action=change_pwd'?>">Change Password</a></li>
              </ul>
            </li> 
          </ul>
		  
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

 <div class="app-content" width="100%">
 <div style="width: 80%">
    <?php 
		echo $this->content;
	?>
 </div> 
        <main class="container">  
				<div style="float: right; width: 20%;">
				<div class="tipbox">
				<div>Instructions</div>
				<form method="post" name="ins_box">
				<input type="hidden" name="page_id" id="page_id" value="">
				<input type="hidden" name="page_name" id="page_name" value="">
				<textarea name="instructions" id="instructions" rows="5" cols="22"><?php echo $this->layout()->instructions; ?></textarea><br>
				<input type="submit" name="ins_submit" id="ins_submit" value="Save">
				</form>
				</div>
			   </div>	
        </main>
</div>
</body>